//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndependentStudy.GoogleMapsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GoogleMapsServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBytesForImage", ReplyAction="http://tempuri.org/IService1/GetBytesForImageResponse")]
        byte[] GetBytesForImage(string location, int zoom, string mapType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLatLongBytesForImage", ReplyAction="http://tempuri.org/IService1/GetLatLongBytesForImageResponse")]
        byte[] GetLatLongBytesForImage(double lat, double lng, string location, int zoom, string mapType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNameURL", ReplyAction="http://tempuri.org/IService1/GetNameURLResponse")]
        string GetNameURL(string location);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : IndependentStudy.GoogleMapsServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<IndependentStudy.GoogleMapsServiceReference.IService1>, IndependentStudy.GoogleMapsServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] GetBytesForImage(string location, int zoom, string mapType) {
            return base.Channel.GetBytesForImage(location, zoom, mapType);
        }
        
        public byte[] GetLatLongBytesForImage(double lat, double lng, string location, int zoom, string mapType) {
            return base.Channel.GetLatLongBytesForImage(lat, lng, location, zoom, mapType);
        }
        
        public string GetNameURL(string location) {
            return base.Channel.GetNameURL(location);
        }
    }
}
